project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "The macroecology of knowledge: Spatio-temporal patterns of name-bearing types in biodiversity science"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "R"
        contents:
          - R/01_D_data_preparation.qmd
          - R/02_A_beta-endemics-countries.qmd
          - R/03_D_data_preparation_models.qmd
          - R/04_A_model_NBTs.qmd
          - R/05_V_chord_diagram_Fig1.qmd
          - R/06_V_world_map_Fig1.qmd
          - R/07_V_scatterplot_Fig2.qmd
          - R/08_V_beta_endemics_Fig3.qmd
          - R/09_V_model_Fig4.qmd
          - R/0010_Supplementary_analysis.qmd
      - section: "Functions"
        contents:
          - R/0012_Functions.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/GabrielNakamura/NBT_code_data

format:
  html:
    theme: cosmo
    toc: true
    code-links:
      - text: Source Code
        icon: file-code
        href: https://github.com/GabrielNakamura/NBT_code_data
